### ISSUE TITLE
Yaacc can't be seen as MediaRenderer

### ISSUE THREAD

**Issue by Eneen** [tobexyz/yaacc-code#38]
I'm trying to setup yaacc as media render on Samsung Galaxy S4 and I'm using foobar2000 media renderer output plugin. Looks like foobar can't see yaacc, but can see bubbleupnp correctly. Media receiver is enabled, I'm not sure what else should be enabled.

**Comment by tobexyz** [comment]
Is bubbleupnp running on the same device? Maybe there is an collision between both renderers?Does the yaacc renderer appears inside yaacc itself?

**Comment by Eneen** [comment]
Yes is does.

**Comment by ccpp** [comment]
I don't know if this is related: videos do not show 8n the player tab anymore, but can only be opened by an external app. Is this known? Should I report separately?

**Comment by tobexyz** [comment]
I can't reproduce it. Please recheck with version 3.0.0

**Comment by ccpp** [comment]
Same in version 3.0.0

**Comment by tobexyz** [comment]
Maybe you expect an behavior which is not implemented:  Videos are only played by an external app. In the app only a "multi player" is shown, which manages the list of items to be played by the external app. That's how it works since the early days of yaacc. Only a music and image player is included in the app directly. Does this answer your question?

**Comment by ccpp** [comment]
Ok thank you for clarification and sorry for abusing this issue. I thought that last time I used this app it behaved differently(i.e., back before #27, #46)

**Comment by tobexyz** [comment]
I'll close this issue because I think it is stale. Please, reopen if the original problem persist
