### ISSUE TITLE
app starts always automaticly on boot

### ISSUE THREAD

**Issue by Boebbele** [tobexyz/yaacc-code#72]
How can I disable autostart?
The app starts on boot automaticly in background.

**Comment by tobexyz** [comment]
Thank's for your report. There are two known options why yaacc is starting:
- you enabled the start of the media server on boot in the settings (I assume you didn't but if so it is the expected behavior :))
- On some devices in some cases yaacc is restarted autonomously. I do not really know why that happens. Maybe this behavior is related to https://github.com/tobexyz/yaacc-code/issues/16#issuecomment-1368709475 A background service is started directly when the app starts. That should be refactored in the way starting the service at the moment when the first player will started and not earlier
For this behavior a workaround is to stop yaacc using the menu item in the option menu of the app.

**Comment by tobexyz** [comment]
will be fixed with upcoming release 4.0.0
