### ISSUE TITLE
Local server should be on on first launch

### ISSUE THREAD

**Issue by exadeci** [tobexyz/yaacc-code#77]
When I launched the app I thought it didn't support casting local media to my TV, I did in the end figure out that local server and content directory needed to be enabled but I feel that not everyone will understand what to do.

Thanks for providing an open source adless DLNA player!

**Comment by tobexyz** [comment]
Hi, thank you for your report. I've to think about it because launching the content directory on startup will share all your media files on the device in your network without any notification about it. Maybe the behavior is changeable if 
- the issue #67 is implemented 
or
- the yaacc media server could be always shown in the server list independently from the state and could enabled by an switch on the entry

**Comment by markfili** [comment]
@tobexyz in the meantime, could you just add a short section "_STARTING THE SERVER: go to Settings and tick some checkboxes under "Local server configuration" in order to start the server_" to README of this project?

**Comment by tobexyz** [comment]
@markfili thanks for the advice. I added a hint to the README

**Comment by tobexyz** [comment]
Today I focused this issue. Now you are able to switch the local server on and off on the main screen. Two icons are showing if receiving and or sending of content is enabled.
I hope this will make the server configuration a bit easier to understand...

![Screenshot_20240120-223952.png](https://github.com/tobexyz/yaacc-code/assets/40026159/dcb98425-955b-4934-964d-0fe220b383ae)
